# Generated by Django 4.1.4 on 2023-06-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=500)),
                ('meeting_link', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=30)),
                ('aspace', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('ip_address', models.CharField(max_length=50)),
            ],
        ),
    ]
