# Generated by Django 4.1.4 on 2023-06-21 06:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_sentmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentmessage',
            old_name='meeting_link',
            new_name='meet_link',
        ),
        migrations.AddField(
            model_name='sentmessage',
            name='sign',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
