# Generated by Django 4.1.4 on 2023-06-21 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_rename_meeting_link_sentmessage_meet_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentmessage',
            old_name='meet_link',
            new_name='meetlink',
        ),
    ]
