# Generated by Django 4.1.4 on 2023-06-21 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_rename_meet_link_sentmessage_meetlink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentmessage',
            old_name='meetlink',
            new_name='meet',
        ),
    ]
