# Generated by Django 4.1.4 on 2023-06-21 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0006_rename_meetlink_sentmessage_meet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentmessage',
            name='aspace',
        ),
        migrations.RemoveField(
            model_name='sentmessage',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='sentmessage',
            name='meet',
        ),
        migrations.RemoveField(
            model_name='sentmessage',
            name='sign',
        ),
        migrations.RemoveField(
            model_name='sentmessage',
            name='time',
        ),
        migrations.RemoveField(
            model_name='sentmessage',
            name='topic',
        ),
    ]
