# Generated by Django 4.1.4 on 2023-06-21 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0007_remove_sentmessage_aspace_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='my contacts')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='group name')),
                ('company', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=12)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message.contacts')),
            ],
        ),
        migrations.CreateModel(
            name='Contact_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=12)),
                ('mycontact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message.contacts')),
            ],
        ),
    ]
