# Generated by Django 4.1.4 on 2023-06-21 13:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0008_contacts_group_contact_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentmessage',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
