# Generated by Django 4.1.4 on 2023-06-22 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0009_sentmessage_sent_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='phone_number',
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=12)),
                ('mycontact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message.group')),
            ],
        ),
    ]
