# Generated by Django 4.1.4 on 2023-06-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0013_remove_member_file_path_group_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='file_path',
            field=models.FilePathField(max_length=200, path='http://127.0.0.1:8000/admin/message/member/'),
        ),
    ]
