# Generated by Django 4.1.4 on 2023-06-26 19:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0017_alter_group_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='ip_address',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
