# Generated by Django 4.1.4 on 2023-06-26 19:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0018_member_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='ids',
            field=models.CharField(default=django.utils.timezone.now, max_length=5),
            preserve_default=False,
        ),
    ]
