# Generated by Django 4.1.4 on 2023-06-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0021_alter_member_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='file_path',
            field=models.FilePathField(max_length=200),
        ),
    ]
