# Generated by Django 4.1.4 on 2023-06-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0025_alter_group_file_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='mycontact',
            new_name='GroupName',
        ),
        migrations.AlterField(
            model_name='group',
            name='file_path',
            field=models.FilePathField(match='sms.*', path='c:/users/samuel pc/downloads/debo/debo/sms/sendsms/message/upload/', recursive=True),
        ),
    ]
