# Generated by Django 4.1.4 on 2023-07-01 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0027_rename_ids_member_group_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='name',
            new_name='group_name',
        ),
    ]
