# Generated by Django 4.1.4 on 2023-07-01 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0028_rename_name_group_group_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='GroupName',
            new_name='group_name',
        ),
    ]
