# Generated by Django 4.1.4 on 2023-07-01 11:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0031_receiver_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='sender',
            name='ip_address',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
