# Generated by Django 4.1.4 on 2023-07-01 11:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0032_sender_ip_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receiver',
            old_name='reciever',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='sender',
            old_name='sender',
            new_name='name',
        ),
        migrations.AddField(
            model_name='receiver',
            name='phone_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sender',
            name='pone_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=12),
            preserve_default=False,
        ),
    ]
