# Generated by Django 4.1.4 on 2023-07-01 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0033_rename_reciever_receiver_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sender',
            name='ip_address',
        ),
    ]
