# Generated by Django 4.1.4 on 2023-07-01 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0034_remove_sender_ip_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sender',
            old_name='pone_number',
            new_name='receiver_number',
        ),
        migrations.RenameField(
            model_name='sender',
            old_name='name',
            new_name='sender_name',
        ),
    ]
