# Generated by Django 4.1.4 on 2023-07-01 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0035_rename_pone_number_sender_receiver_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sender',
            old_name='receiver_number',
            new_name='sender_number',
        ),
        migrations.AlterField(
            model_name='member',
            name='group_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grs', to='message.group'),
        ),
    ]
