# Generated by Django 4.1.4 on 2023-07-03 13:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0036_rename_receiver_number_sender_sender_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentmessage',
            name='rec_phone_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sentmessage',
            name='receiver_name',
            field=models.CharField(default='sami', max_length=50),
            preserve_default=False,
        ),
    ]
