# Generated by Django 4.1.4 on 2023-07-03 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0037_sentmessage_rec_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentmessage',
            name='receiver',
            field=models.ManyToManyField(to='message.receiver'),
        ),
    ]
