# Generated by Django 4.1.4 on 2023-07-04 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0038_sentmessage_receiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentmessage',
            name='receiver',
        ),
    ]
