# Generated by Django 4.1.4 on 2023-07-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0039_remove_sentmessage_receiver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('subject', models.CharField(max_length=300)),
                ('message', models.CharField(max_length=1000)),
            ],
        ),
    ]
