# Generated by Django 4.1.4 on 2023-07-07 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0040_contactus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='file_path',
        ),
    ]
