# Generated by Django 4.1.4 on 2023-07-08 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0042_canviewowngroup_alter_group_options_group_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={},
        ),
        migrations.AlterField(
            model_name='member',
            name='group_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grs', to='message.group'),
        ),
    ]
