# Generated by Django 4.1.4 on 2023-07-08 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import message.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('message', '0043_alter_group_options_alter_member_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='user',
            field=models.ForeignKey(default=message.models.get_default_user_id, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
