# Generated by Django 4.1.4 on 2023-08-22 13:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('message', '0046_chapatransaction_delete_customuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='Group_Created',
        ),
    ]
