# Generated by Django 4.1.4 on 2023-08-22 13:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('message', '0047_rename_group_group_created'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group_Created',
            new_name='Created_Group',
        ),
    ]
