"""
Django settings for sendsms project.

Generated by 'django-admin startproject' using Django 4.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os
from .config import SECRET_KEY,  EMAIL_HOST_PASSWORD,EMAIL_HOST_USER,SOCIAL_AUTH_FACEBOOK_KEY,SOCIAL_AUTH_FACEBOOK_SECRET
from.config import  SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET,SOCIAL_AUTH_GOOGLE_OAUTH2_KEY
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
EMAIL_BACKEND ='django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'

# EMAIL_HOST_USER='samimokehirpa@gmail.com'
EMAIL_HOST_USER=EMAIL_HOST_USER

# EMAIL_HOST_PASSWORD='gwczutsvofedcsiv'
EMAIL_HOST_PASSWORD= EMAIL_HOST_PASSWORD

EMAIL_PORT ='587'

EMAIL_USE_TLS =True 
PASSWORD_RESET_TIMEOUT=14400



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-t@a+e=lj4*=@^z%(wpbp^n+b@s9z5vpggvkc7j0*%==+#&gii^'
SECRET_KEY=SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # 'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'message',
    'social_django',
    'sslserver',
    'chartjs',
    
    
    'allauth.socialaccount.providers.google',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware',
]

ROOT_URLCONF = 'sendsms.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
                
            ],
        },
    },
]

WSGI_APPLICATION = 'sendsms.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_URL = 'BASE-DIR/static/'
MEDIA_URL='/assets/images/'
# STATICFILES_DIRS=[
#     BASE_DIR /'static',
    
# ]
MEDIA_ROOT=BASE_DIR / 'static/assets/img'
LOGIN_URL='/login/'
LOGIN_REDIRECT_URL='choice'


LOGOUT_REDIRECT_URL = "/login/"
# EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

AUTHENTICATION_BACKENDS = (
    'social_core.backends.facebook.FacebookOAuth2',
    'social_core.backends.google.GoogleOAuth2',
    'social_core.backends.twitter.TwitterOAuth',
    'social_core.backends.github.GithubOAuth2',

    'django.contrib.auth.backends.ModelBackend',
)
# SOCIAL_AUTH_FACEBOOK_KEY='1002584504211501'
SOCIAL_AUTH_FACEBOOK_KEY=SOCIAL_AUTH_FACEBOOK_KEY
# SOCIAL_AUTH_FACEBOOK_SECRET='d6bfdac15d8cca0cbe955c3e63480ab2'
SOCIAL_AUTH_FACEBOOK_SECRET=SOCIAL_AUTH_FACEBOOK_SECRET

# SOCIAL_AUTH_GOOGLE_OAUTH2_KEY='307177788408-5u7oou1od71q3cf76187cvdeh3a74oha.apps.googleusercontent.com'
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY=SOCIAL_AUTH_GOOGLE_OAUTH2_KEY
# SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET='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'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET= SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET

# SOCIAL_AUTH_LOGIN_ERROR_URL = '/settings/'
# SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/settings/'
SOCIAL_AUTH_RAISE_EXCEPTIONS = False
SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE = [
    'https://www.googleapis.com/auth/userinfo.email',
    'https://www.googleapis.com/auth/userinfo.profile'
]
SOCIAL_AUTH_URL_NAMESPACE = 'social'
SOCIAL_AUTH_GOOGLE_OAUTH2_AUTH_EXTRA_ARGUMENTS = {
    'access_type': 'offline'
}
SITE_ID=1
# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

if DEBUG:
    # Redirect all HTTP traffic to HTTPS in development
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
# SESSION_COOKIE_SECURE = False
# CSRF_COOKIE_SECURE = False
# SOCIAL_AUTH_REDIRECT_IS_HTTPS = False
